name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  star:
    runs-on: ubuntu-latest

    container:
      image: rakudo-star:latest

    steps:
    - uses: actions/checkout@v3

    - name: Raku version
      run: raku -v

    - name: apt update
      run:  apt-get -qq update -y

    - name: install libsodium
      run:  apt-get -qq install -y libsodium23

    - name: Install dependencies
      run: zef install --deps-only --/test --force-install --test-depends .

    - name: Run tests
      run: zef test -v --debug .

  alpine:
    runs-on: ubuntu-latest

    container:
      image: rakudo-star:alpine

    steps:
    - uses: actions/checkout@v3

    - name: Raku version
      run: raku -v

    - name: install libsodium
      run:  apk add libsodium

    - name: Install dependencies
      run: zef install --deps-only --/test --force-install --test-depends .

    - name: Run tests
      run: zef test -v --debug .
